import { readFileSync, writeFileSync, copyFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

const distDir = resolve('dist');
const srcFile = resolve('dist/search-index.json');
const destFile = resolve('dist/search-index.json');

if (!existsSync(srcFile)) {
  console.error('⚠️  search-index.json not generated by astro build');
  process.exit(0);
}

// astro build writes to dist/search-index.json; ensure filename stays the same
console.log('✓ search-index.json present');